spring:
  application:
    name: accountservice  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trukeaaccountservicedb
    username: scott
    password: tiger
  jpa:    show-sql: true
    generate-ddl: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    
server:  port: 8081
 