spring:
  mvc:
    static-path-pattern: /assets/**

server:
  port: 8080
  
accountService:
  url: http://localhost:8081
  apiKey: acheter_customer_web
  secret: Abcd1234@
    
adsTradingService:
  url: http://localhost:8082  